### ISSUE TITLE
Usage with Lambda@Edge

### ISSUE THREAD

**Issue by dtothefp** [DataDog/datadog-lambda-js#102]
## Expected Behavior
Aggregate logs from multiple regions into DataDog from Lambda@Edge

## Actual Behavior
Not sure...not seeing logs. We setup Forwarders in multiple regions but are unsure how / if to use this package in combination with that.

https://github.com/DataDog/datadog-serverless-functions/issues/359

## Steps to Reproduce the Problem
For our non Lambda@Edge Lambdas I use the [Serverless Plugin Datadog](https://github.com/DataDog/serverless-plugin-datadog) in combination with this datadog-lambda-js library and we see consistent logs / traces in DataDog

![Screen Shot 2020-09-25 at 12 43 18 PM](https://user-images.githubusercontent.com/4656726/94309321-bd6e7c80-ff2c-11ea-8aea-46a36091c8b2.png)

When using Lambda@Edge Cloudwatch logs occur in the AWS region where the request is routed to. We have setup forwarders in multiple regions but still are seeing no logs. I tried wrapping my handler in the `datadog` function and tried variations both with:

```js
process.env.DD_FLUSH_TO_LOG = 'false';
```

and

```js
process.env.DD_FLUSH_TO_LOG = 'true';
process.env.DD_SITE = 'datadoghq.com';
process.env.DD_API_KEY = dataDogApiKey
```

## Specifications

  - Datadog Lambda Layer version: ?
  - Node version:  12.x

**Comment by tianchu** [comment]
Thanks for your feedback @dtothefp!

I responded on the linked issue for Forwarder, but basically due to the [complex limits and restrictions on Lambda@Edge functions](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/lambda-requirements-limits.html), the Datadog Lambda library does not yet really work for lambda@edge.

Do you mind submitting an official feature request to support@datadoghq.com instead? I'm going to close this issue for now, since there is no immediate actions we can take here.

**Comment by chandywerks** [comment]
Is this still true? The documentation here implies that Lambda@Edge is supported.

https://docs.datadoghq.com/serverless/serverless_integrations/#lambdaedge

**Comment by tianchu** [comment]
@chandywerks nothing really changed since then. Those tags mentioned in the doc are automatically enriched my our AWS integration, and it doesn't depend on our Lambda library.

**Comment by w3nda** [comment]
@tianchu any update here?

**Comment by dr-bizz** [comment]
Any update here?

**Comment by JanGanaCode** [comment]
any update here?  🙂

**Comment by edtep-relayfi** [comment]
@tianchu any update here?

**Comment by artem-pdus** [comment]
any update here?

**Comment by chandywerks** [comment]
Try this, https://github.com/chandywerks/terraform-datadog-cloudwatch
