### ISSUE TITLE
Webpack bundling is not able to resolve dependencies statically

### ISSUE THREAD

**Issue by omakoleg** [DataDog/datadog-lambda-js#108]
## Expected Behavior

No warnings in webpack bundling process.

## Actual Behavior

Warnings in bundle output:
```

WARNING in ./node_modules/datadog-lambda-js/dist/trace/tracer-wrapper.js 33:23-30
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 @ ./node_modules/datadog-lambda-js/dist/trace/listener.js
 @ ./node_modules/datadog-lambda-js/dist/trace/index.js
 @ ./node_modules/datadog-lambda-js/dist/index.js

WARNING in ./node_modules/datadog-lambda-js/dist/trace/tracer-wrapper.js 34:26-39
Critical dependency: the request of a dependency is an expression
 @ ./node_modules/datadog-lambda-js/dist/trace/listener.js
 @ ./node_modules/datadog-lambda-js/dist/trace/index.js
 @ ./node_modules/datadog-lambda-js/dist/index.js

```

## Steps to Reproduce the Problem

Have library imported in code:
```ts
import { datadog, sendDistributionMetric } from 'datadog-lambda-js'
```
And then trying to make webpack bundle

So far not observed influence on running application, but warnings are printed each time.

This happens because of dynamic module names could be used in `require` so webpack cant resolve them when building bundle form all sources linked together.

**Comment by tamj0rd2** [comment]
Did you find a workaround for this?

**Comment by tianchu** [comment]
For whoever run into issues when using webpack, please check out https://docs.datadoghq.com/serverless/troubleshooting/serverless_tracing_and_webpack.

**Comment by tamj0rd2** [comment]
> For whoever run into issues when using webpack, please check out https://docs.datadoghq.com/serverless/troubleshooting/serverless_tracing_and_webpack.

If the import is removed, how can you call `sendDistributionMetric` for custom metrics?

**Comment by tianchu** [comment]
@tamj0rd2 Yes, the datadog-lambda-js is included in our Datadog Lambda Layer, and the layer should be installed to your function if following one of the official installation methods https://docs.datadoghq.com/serverless/installation/nodejs.

**Comment by tamj0rd2** [comment]
I'm still confused. Can you give an example of how this is supposed to work?

I've removed 'datadog-lambda-js' from my list of dependencies and all of the imports such as `import { datadog, sendDistributionMetric } from 'datadog-lambda-js'`. Now from my code, how do I call sendDistributionMetric. If I try to call that function without importing it from anywhere, my lambda throws the error `sendDistributionMetric is not defined` which means the function isn't in the global scope. How can I get access to it?

The links you've sent are contradictory unless I'm just misunderstanding how this should work? The first link says to remove the imports but then the second link uses the imports.

**Comment by tianchu** [comment]
@tamj0rd2 The doc says to "Remove datadog-lambda-js and dd-trace from your package.json and the build process.". But you do not need to remove the "import" statements from your code, the import statement should still work, because they will import the packages from the layer `arn:aws:lambda:${region}:464622532012:layer:Datadog-Node14-x:51`.

**Comment by tianchu** [comment]
The gist here is that our layers installs the required packages to your runtime, so your application can "import" and "call" functions like `sendDistributionMetric`. Because these packages already exist in your runtime, you need to mark them as "external" to webpack to excluding them from the bundling process.

**Comment by tianchu** [comment]
I will update that doc to explain this a little bit better now that I see how does it create the confusion. Thanks for flagging this to us 🙇

**Comment by tamj0rd2** [comment]
Thanks for explaining that. I've got it working now 🙌

**Comment by FizzBuzz791** [comment]
@tianchu - the docs still say "remove from your package.json" and it confused us for a long time until we found this thread. I think something like "move 'datadog-lambda-js' to your devDependencies" would be clearer.
