### ISSUE TITLE
Need to close socket

### ISSUE THREAD

**Issue by michael-jennings-evive** [DataDog/datadog-lambda-js#113]
https://github.com/DataDog/datadog-lambda-js/blob/b968303cf69eb33d63bed4588c465c611cd091c4/src/trace/context.ts#L134

Socket is opened but never closed.  This causes our application host to run out of file descriptors.  We need to restart the host to recover lost resources.

**Datadog lambda layer version:**
`"datadog-lambda-js": "^3.27.0"`

**Node version:**
12.x (whatever AWS lambda uses)

Error logs:
```
{
    "error": {
        "message": "getaddrinfo EMFILE dynamodb.us-east-1.amazonaws.com",
        "errno": "EMFILE",
        "code": "NetworkingError",
        "syscall": "getaddrinfo",
        "hostname": "dynamodb.us-east-1.amazonaws.com",
        "region": "us-east-1",
        "retryable": true,
        "time": "2020-10-15T09:34:05.022Z"
    },
    "request_id": "be84c269-b2eb-4fbc-82bf-202c9e12ec62",
    "stack_trace": [
        {
            "function_name": "processTicksAndRejections",
            "file": {
                "name": "internal/process/task_queues.js",
                "location": {
                    "line": 97,
                    "column": 5
                }
            }
        }
    ],
    "dd": {
        "trace_id": "2308384582283572634",
        "span_id": "6702646418954244696",
        "service": "xxx",
        "env": "xxx"
    }
}
```

**Comment by DarcyRaynerDD** [comment]
Hi @michael-jennings-evive, thanks for the detailed report. I've just released v3.34.0, which has a fix for this issue. Can you confirm whether it works for you?
