### ISSUE TITLE
Question: Custom logger using Datadog lambda layer

### ISSUE THREAD

**Issue by bryantbiggs** [DataDog/datadog-lambda-js#143]
When using the Datadog lambada layer which contains the `datadog-lambda-js` lib, what is the recommended approach to utilize a custom logger implementation like shown on the [README example](https://github.com/DataDog/datadog-lambda-js#custom-logger)?

**Comment by tianchu** [comment]
@bryantbiggs do you mind elaborating on your situation and goal?
