### ISSUE TITLE
Question: AWS SDK Lambda invoke tracing

### ISSUE THREAD

**Issue by Padwicker** [DataDog/datadog-lambda-js#167]
Hey

In the [distributed tracing docs](https://docs.datadoghq.com/serverless/distributed_tracing/) it says 

> Tracing synchronous Lambda invokes with the AWS SDK (coming soon for Node.js).
> Tracing asynchronous Lambda invocations through AWS SQS (coming soon for Node.js).

Is there a rough timeline for when this will be ready?

**Comment by tianchu** [comment]
@Padwicker it was released yesterday https://github.com/DataDog/datadog-lambda-js/releases/tag/v3.49.1 :)
