### ISSUE TITLE
Please fix DeprecationWarning caused by Buffer initialization

### ISSUE THREAD

**Issue by vence722** [DataDog/datadog-lambda-js#168]
https://github.com/DataDog/datadog-lambda-js/blob/main/src/trace/context.ts#L165

This line will generate the DeprecationWarning: "Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead."

This warning will be printed as error by Node.js 14 Runtime, so it'll generate a lot of error log events in Datadog. Hope you can fix this issue in the future version. Thanks a lot.

**Comment by DarcyRaynerDD** [comment]
👋 Hi @vence722 . Thanks for the report. I've just merged a fix for this, and we will roll it out with the next release.
