### ISSUE TITLE
A BadRequest response from the API logs `authorization failed...`

### ISSUE THREAD

**Issue by Czechh** [DataDog/datadog-lambda-js#170]
## Expected Behavior
On a BadParam Error from the API, don't log that there is an authorization failure.

## Actual Behavior
On a BadParam Error from the API we log the following line https://github.com/DataDog/datadog-lambda-js/blob/main/src/metrics/api.ts#L28 - as this check puts the response in the same bucket https://github.com/DataDog/datadog-lambda-js/blob/main/src/utils/request.ts#L56.

So the request is rejected with a `BadAuth`

## Steps to Reproduce the Problem

  0. Turn on debug mode
  1. Send a malformed metric
  2. Check the logs

## Specifications

  - Datadog Lambda Layer version: 3.49.1
  - Node version: 14.x

**Comment by nhinsch** [comment]
👋

**Comment by tianchu** [comment]
@nhinsch You mind owning this one?

**Comment by nhinsch** [comment]
This should be fixed by https://github.com/DataDog/datadog-lambda-js/pull/210

The change will be included in the next release of the library.
