### ISSUE TITLE
Feature Request: Support a less invasive way of instrumenting lambdas

### ISSUE THREAD

**Issue by kbkk** [DataDog/datadog-lambda-js#239]
## Expected Behavior

I can set `AWS_LAMBDA_EXEC_WRAPPER` pointing to DD Lambda layer without touching anything else in the Lambda configuration in order to get tracing.

Here's an example of a similar tracing solution (OpenTelemetry): https://github.com/open-telemetry/opentelemetry-lambda/blob/main/nodejs/README.md

## Actual Behavior

The current behavior is a terrible DX choice IMO:
- I have to change my main lambda handler to `/opt/nodejs/node_modules/datadog-lambda-js/handler.handler`
- Then I can configure `DD_LAMBDA_HANDLER` with my actual handler function

**Comment by tianchu** [comment]
@kbkk Thanks again for flagging this idea! Since we are already planning something similar internally while do not plan to directly work against this "issue" in the near future, I'm going to close this thread for hygiene. 🙇‍♂️
