### ISSUE TITLE
DataDog Layer doesn't support arm architecture

### ISSUE THREAD

**Issue by pauloprestes** [DataDog/datadog-lambda-js#250]
## Expected Behavior

The Lambda to work with datadog and ARM architecture.

## Actual Behavior

Lambda deployed using ARM architecture doesn't work with datadog layer.

## Steps to Reproduce the Problem

  1. Deploy lambda using ARM architecture.

## Specifications

  - Datadog Lambda Layer version: 65
  - Node version: 14.x

## Stacktrace

  ```
RequestId: $$$$ Error: fork/exec /opt/extensions/datadog-agent: exec format error
Extension.LaunchError
  ```

**Comment by maxday** [comment]
👋  It seems that you're using the Datadog Extension as well. I think you might have the layer built for the wrong architecture.
If you are using the ARM architecture, make sure you've selected the -ARM suffixed layer.
You can find the latest arn values here : https://github.com/DataDog/datadog-lambda-extension/releases

**Comment by pauloprestes** [comment]
Thanks @maxday , after changing the datadog extension it did work.
