### ISSUE TITLE
Custom Metrics

### ISSUE THREAD

**Issue by sugendran** [DataDog/datadog-lambda-js#255]
Hi,

I'd like to use a scheduled lambda to create some custom metrics. As I understand it, I can use this library to give me metrics about that lambda's execution, but I cannot use it to create custom metrics such as a gauge. Could you expose the current metric listener so that we can submit custom metrics?

Thanks

**Comment by agocs** [comment]
Hi @sugendran! You can submit custom distribution metrics from within your lambda functions. Here's a code sample: 

```js
const { sendDistributionMetric } = require('datadog-lambda-js');

async function myHandler(event, context) {
    sendDistributionMetric(
        'coffee_house.order_value', // Metric name
        12.45, // Metric value
        'product:latte', // First tag
        'order:online' // Second tag
    );
    return {
        statusCode: 200,
        body: 'hello, dog!'
    };
}
```

We have some [more information here](https://docs.datadoghq.com/serverless/custom_metrics/#custom-metrics-sample-code)

You can read more about [distribution metrics here.](https://docs.datadoghq.com/metrics/types/?tab=distribution#metric-types)

Unfortunately, we can't support Count, Rate, Gauge, or Histogram metrics from a serverless context. When multiple of those metrics are submitted at approximately the same time (e.g. from concurrent lambda executions), our metrics intake treats them as duplicates and discards all but the last metric received. Distribution metrics are aggregated on the back end instead, and you can treat them the same as rates, gauges, etc., from within Datadog.

Let me know if you have any further questions!

**Comment by sugendran** [comment]
I get the issue with real time collection, but what about for cases where we set a specific timestamp?  Even if the lambda were to run as a second instance it would overwrite the prior entry, right?

**Comment by agocs** [comment]
If you are using distribution metrics like in the example above, you would not overwrite a metric even if you were sending the exact same timestamp.

**Comment by tianchu** [comment]
This is now better explained in https://docs.datadoghq.com/serverless/custom_metrics#understanding-distribution-metrics. Closing.
