### ISSUE TITLE
Inferred spans feature breaks when Kinesis stream is gzip encoded

### ISSUE THREAD

**Issue by vvo** [DataDog/datadog-lambda-js#264]
## Expected Behavior

When using the default value of DD_TRACE_MANAGED_SERVICES (true) and your Kinesis stream is encoded in gzip/deflate then a JSON.parse error is thrown.

This is because the stream we're dealing with is encoded in gzip. This is the case when using https://github.com/aws/amazon-kinesis-streams-for-fluent-bit in an infrastructure.

~Thankfully this can be disabled with `DD_TRACE_MANAGED_SERVICES=false`.~ Update: this parameter does not work to disable the error as seen here: https://github.com/DataDog/datadog-lambda-js/issues/264#issuecomment-1054341133

## Actual Behavior

This should either work or not throw by default.

## Steps to Reproduce the Problem

  1. Create a Kinesis stream
  1. Encode records with gzip
  1. Use this extensions

## Specifications

  - Datadog Lambda Layer version: 68
  - Node version: 14.17.6

## Stacktrace

  ```
SyntaxError: Unexpected token  in JSON at position 0
    at JSON.parse (<anonymous>)
    at readTraceFromKinesisEvent (/opt/nodejs/node_modules/datadog-lambda-js/trace/context.js:254:35)
    at readTraceFromEvent (/opt/nodejs/node_modules/datadog-lambda-js/trace/context.js:451:16)
    at extractTraceContext (/opt/nodejs/node_modules/datadog-lambda-js/trace/context.js:55:17)
    at TraceContextService.extractHeadersFromContext (/opt/nodejs/node_modules/datadog-lambda-js/trace/trace-context-service.js:26:67)
    at TraceListener.onStartInvocation (/opt/nodejs/node_modules/datadog-lambda-js/trace/listener.js:95:52)
    at /opt/nodejs/node_modules/datadog-lambda-js/index.js:149:56
    at step (/opt/nodejs/node_modules/datadog-lambda-js/index.js:44:23)
    at Object.next (/opt/nodejs/node_modules/datadog-lambda-js/index.js:25:53)
    at /opt/nodejs/node_modules/datadog-lambda-js/index.js:19:71
  ```

**Comment by vvo** [comment]
cc @astuyve since you introduced the feature, 🙏

**Comment by astuyve** [comment]
@vvo - thanks for the report! This error should be [caught](https://github.com/DataDog/datadog-lambda-js/blob/main/src/trace/context.ts#L280) and logged, so it shouldn't halt lambda progression. But I will attempt to recreate this behavior in order to support tracing across Kinesis streams when data is gzipped.

Thanks!

**Comment by astuyve** [comment]
Thanks @vvo!

The benefit is tracing and monitoring managed services - you can read more here https://www.datadoghq.com/blog/monitor-aws-fully-managed-services-datadog-serverless-monitoring/
This includes quantile metrics for latency.

You can disable it with `DD_TRACE_MANAGED_SERVICES=false`, as per the [readme](https://github.com/DataDog/datadog-lambda-js#dd_trace_managed_services)

Perhaps we can expose the decoded and unzipped payload alongside the original payload, offering consumers the ability to read the already parsed data? Alternatively you can reconstruct trace context [manually](https://docs.datadoghq.com/serverless/distributed_tracing/serverless_trace_propagation/?tab=eventbridge#sample-extractors)

**Comment by vvo** [comment]
>Perhaps we can expose the decoded and unzipped payload alongside the original payload, offering consumers the ability to read the already parsed data?
Yes that would be ideal indeed.

> You can disable it with DD_TRACE_MANAGED_SERVICES=false, as per the [readme](https://github.com/DataDog/datadog-lambda-js#dd_trace_managed_services)

Thanks I've done that but that doesn't get rid of the error because datadog-lambda-js still tries to decode the data. The parameter only influences whether or not the span is created I believe (from reading the code).

**Comment by astuyve** [comment]
Correct, I amended my earlier comment which I posted too quickly.
