### ISSUE TITLE
Support OpenSearch as a Plugin

### ISSUE THREAD

**Issue by zomgbre** [DataDog/datadog-lambda-js#299]
## Expected Behavior
I see that Elasticsearch is available as an instrumentation plugin. Could we also have one for OpenSearch since it is a fork? I haven't tried using Elasticsearch library yet in place of it.

## Actual Behavior
No plugin for OpenSearch.

**Comment by DarcyRaynerDD** [comment]
Hi @zomgbre, thanks for the feature request. It's probably better to create an issue upstream on the [dd-trace-js](https://github.com/Datadog/dd-trace-js) library, which is where all our plugins are implemented, including the Elasticsearch plugin. You could also email support@datadoghq.com, and request the feature there. I'm going to close this issue for now.
