### ISSUE TITLE
Pls update broken link in readme

### ISSUE THREAD

**Issue by anjakunkel** [DataDog/datadog-lambda-js#371]
## Expected Behavior
When following the readme, I know how to use the library.

## Actual Behavior
Readme contains a link to https://docs.datadoghq.com/serverless/configuration that leads to 404. Thus I do not know how to configure the library.

## Specifications

  - branch: main (2023-03-28)

Thank you!

**Comment by anjakunkel** [comment]
Fancy. That works. Now I am really surprised. I did not try that, as I expected simple links to just work ...
Any idea why that link might be dependent on something cached?

**Comment by astuyve** [comment]
Hi @anjakunkel - Good question.

In the case for one browser on my machine, it seems that a 302 redirect is being cached on disk:
<img width="453" alt="image" src="https://user-images.githubusercontent.com/1598537/228272433-f22d7a16-2bd6-4cf8-97eb-f78a1aa05359.png">

Presumably this will resolve as individual browser caches are expired at whatever cadence this occurs. I've asked the docs team to investigate this as well.

Thanks!
