### ISSUE TITLE
Empty array somehow is not shown in the Lambda response when capturing Lambda payloads

### ISSUE THREAD

**Issue by rdsedmundo** [DataDog/datadog-lambda-js#386]
## Expected Behavior
`function.response.body` should be set to `[]`.

## Actual Behavior

<img width="453" alt="Screenshot 2023-04-26 at 3 20 10 PM" src="https://user-images.githubusercontent.com/5482378/234625701-e3630b58-7cf3-4b7b-bcfc-8af97176fcc0.png">

I matched the requests via AWS's Lambda Request ID so I'm sure they're referring to the same request. The same endpoint is working fine for requests that return data in the array: `body[*].A, body[*].B, etc` gets filled correctly.

## Steps to Reproduce the Problem

1. Return an empty array from a Lambda using an HTTP API integration.

It's very hard for me to pinpoint if the bug really is here in this lib, as the bug can be on Datadog's own FE dashboard / API, etc.

## Specifications

  - Datadog Lambda Layer version: 5.17.0
  - Node version: 18.15.0

## Stacktrace

N/A.

**Comment by astuyve** [comment]
Hi @rdsedmundo - thanks for reaching out!

Datadog APM span tags which contain no values are dropped, which is why this is not being shown.
Unfortunately this library doesn't control that, however you could open a feature request with our support team if you'd like to request this.

Thanks!
AJ
