### ISSUE TITLE
Full aws-sdk v3 support for nodejs18.x - remove v2 leftovers

### ISSUE THREAD

**Issue by ThomSMG** [DataDog/datadog-lambda-js#395]
## Expected Behavior

No aws-sdk v2 dependencies

## Actual Behavior

Still hidden (as in: not obvious from package.json dependencies) aws-sdk v2 dependencies - e.g. [kms-service](https://github.com/DataDog/datadog-lambda-js/blob/main/src/metrics/kms-service.ts) depends on `aws-sdk/clients/kms`. The source code comment and rationale
```
// In order to avoid the layer adding the 40mb aws-sdk to a deployment, (which is always available
// in the Lambda environment anyway), we use require to import the SDK.
```
is since nodejs18.x not correct anymore. So basically, if I want to use this library in a lambda with nodejs18.x runtime, I need to bundle in the whole aws-sdk-v2 code into the lambda code. 

## Specifications

  - Datadog Lambda Layer version: 7.9.x
  - Node version: 18

## Stacktrace

  ```
 ../app/node_modules/datadog-lambda-js/dist/metrics/kms-service.js:54:38:
      54 │                         kms = require("aws-sdk/clients/kms");
         ╵                                       ~~~~~~~~~~~~~~~~~~~~~

  ```

**Comment by tianchu** [comment]
@ThomSMG To confirm, you need to submit custom metrics using the datadog-lambda-js alone? (aka, without using the forwarder or extension to submit them asynchronously)

**Comment by talberkoMelio** [comment]
Any update on this? 
I have node 18 lambda, using aws sdk 3, but cannot run as datadog latest layer still using aws-sdk 2:
`Runtime.ImportModuleError: Error: Cannot find module 'aws-sdk'`

**Comment by astuyve** [comment]
Hey folks, sorry for the delay. I will be working on this next.

For now I'd suggesting using another API key installation method, or providing the aws-sdk v2 dependency explicitly.

Thanks!

**Comment by fredrik-eklund** [comment]
any updates on this?

**Comment by astuyve** [comment]
Hi @fredrik-eklund - I'm actively working on this now, but I'm curious why webpack would try to include this? We [conditionally import the KMS Client](https://github.com/DataDog/datadog-lambda-js/blob/main/src/metrics/listener.ts#L182) only if the `DD_KMS_API_KEY` environment variable is present. Can you share more information?

**Comment by astuyve** [comment]
Hey folks, thanks for being patient with me - there was a holiday in the US and I was off for a bit, and had to deal with some other issues.

I've got a fix working which should be available soon, although I'm unsure it'll help in the webpack case as I don't quite understand that repro case.

I'll update this ticket with the PR when it is ready.

**Comment by astuyve** [comment]
Released in https://github.com/DataDog/datadog-lambda-js/releases/tag/v7.94.0
