### ISSUE TITLE
[Feature request] Support Vault for Datadog API Key fetching

### ISSUE THREAD

**Issue by hjfitz** [DataDog/datadog-lambda-js#396]
Is it on the roadmap to support Hashicorp vault?

## Expected Behavior

Support vault to fetch the Datadog API Key

## Actual Behavior

Only AWS Secrets Manager is supported

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Datadog Lambda Layer version:
  - Node version:

## Stacktrace

  ```
  Paste here
  ```

**Comment by tianchu** [comment]
@hjfitz Are you able to resolve the API Key from Vault at the build time? So you don't need to hardcode the api key in project definition, but you would still have the api key exposed through the Lambda console.

Anyway, we might need to park the request here for a while to gauge the demand first before we can prioritize anything, given that this is the first time we hear about this.

**Comment by hjfitz** [comment]
@tianchu Yeah, there was the option to grab it and toss it in to env with my terraform setup, but the security requirements are a little higher for this particular project. 

We’re happy using our log forwarder, for now though 🙂

**Comment by tianchu** [comment]
Closing due to lack of activities. For anyone else running into the similar need, feel free to reopen or submit a FR through the Datadog Support.
