### ISSUE TITLE
Path is removed by SAM CLI v1.89. 

### ISSUE THREAD

**Issue by ruiwei** [DataDog/datadog-lambda-js#401]
## Expected Behavior
The handler is "/opt/nodejs/node_modules/datadog-lambda-js/handler.handler"

## Actual Behavior
SAM CLI v1.89 removed the path, so it is "handler.handler" now. 
The example of using layer is not working anymore.

## Specifications

  - Datadog Lambda Layer version: Any
  - Node version: Any

This is the bug report on SAM CLI
https://github.com/aws/aws-sam-cli/issues/5429
https://github.com/aws/aws-sam-cli/pull/4216

**Comment by astuyve** [comment]
Hi @ruiwei - thanks for reaching out!

It seems like this is a bug in SAM and not Datadog, in fact after looking at the post you linked I'm not sure there's anything we can do except ask the AWS team to followup and offer a workaround for this, as it seems that this was a breaking change.

Thanks!

**Comment by ruiwei** [comment]
@astuyve Yeah. Can we keep this issue open? This may help other people in a similar situation. 
 It took me a while to figure out why the SAM build did not work after being deployed by GitHub Actions.

**Comment by astuyve** [comment]
Sure thing, we'll keep this open until we can figure something out with SAM.

Thanks!

**Comment by astuyve** [comment]
This is [released](https://github.com/aws/aws-sam-cli/issues/5429#event-9853855825) in [1.91.](https://github.com/aws/aws-sam-cli/releases/tag/v1.91.0)
