### ISSUE TITLE
Missing KMS client dependency

### ISSUE THREAD

**Issue by MattTennison** [DataDog/datadog-lambda-js#408]
## Expected Behavior

NodeJS functions build in CDK

## Actual Behavior

CDK fails to build due to:
```
Error: R] Could not resolve "@aws-sdk/client-kms"

    node_modules/datadog-lambda-js/dist/metrics/kms-service.js:100:37:
      100 │ ...        _a = require("@aws-sdk/client-kms"), KMSClient = _a.KM...
          ╵                         ~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@aws-sdk/client-kms" as external to exclude it from the bundle, which will remove this error. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.
```

This has only just started happening - 7.93.0 works fine. I think it's because the KMS client was added as a dev dependency, but appears to be used in runtime code.

## Steps to Reproduce the Problem

  1. Create CDK project without `@aws-sdk/client-kms` dependency
  2. Create a NodeJS function in a CDK stack and add it to the datadog construct
  3. Attempt to build or deploy the stack

## Specifications

  - Datadog Lambda Layer version: 7.94.0
  - Node version: 16.20.1

## Stacktrace

  ```
Error: R] Could not resolve "@aws-sdk/client-kms"

    node_modules/datadog-lambda-js/dist/metrics/kms-service.js:100:37:
      100 │ ...        _a = require("@aws-sdk/client-kms"), KMSClient = _a.KM...
          ╵                         ~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@aws-sdk/client-kms" as external to exclude it from the bundle, which will remove this error. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.
  ```

**Comment by astuyve** [comment]
Hi,
Thanks for reaching out! Indeed this has been added to support node18 which includes the aws-sdk v3 by default.

Although not explicitly wrapped in try/catch, the `require` is made [conditionally](https://github.com/DataDog/datadog-lambda-js/blob/main/src/metrics/kms-service.ts#L37-L39) and the top-level call is in a try/catch [block](https://github.com/DataDog/datadog-lambda-js/blob/main/src/metrics/listener.ts#L180-L185).

My guess is that esbuild doesn't realize this and complains when bundling the file.

For now, please mark `@aws-sdk/client-kms` as external and I can experiment with more explicit ways to satisfy the bundler.

Thanks!

**Comment by MattTennison** [comment]
Brill, thanks for fixing it @astuyve. Our build pipeline is happy with v7.95.0 so looks to have worked 😄

**Comment by astuyve** [comment]
You bet, glad it's working! I documented the issue in the PR in case future contributors/customers have questions.

Thanks again!
