### ISSUE TITLE
Merge with standard W3C trace context

### ISSUE THREAD

**Issue by drunkirishcoder** [DataDog/datadog-lambda-js#414]
## Expected Behavior

If there's an ongoing W3C trace context, this should automatically extract and merge with that. Based on the documentation, dd-trace seems to support that,

```
DD_TRACE_PROPAGATION_STYLE
Configuration: tracePropagationStyle
Default: Datadog,tracecontext
A comma-separated list of header formats from which to attempt to inject and extract distributed tracing propagation data. The first format found with complete and valid headers is used to define the trace to continue. The more specific DD_TRACE_PROPAGATION_STYLE_INJECT and DD_TRACE_PROPAGATION_STYLE_EXTRACT configurations take priority when present.
```

## Actual Behavior

Was not able to get this behavior using the lambda extension with nodejs18. Looking through [the codebase](https://github.com/DataDog/datadog-lambda-js/blob/main/src/trace/constants.ts), it doesn't seem like this is supported.

## Steps to Reproduce the Problem

  1. start an opentelemetry trace in a different micro-service, sent to datadog
  1. micro service calls into the lambda function via API gateway
  1. the lambda function starts a new trace context, did not merge with the existing trace context

## Specifications

  - Datadog Lambda Layer version: 90
  - Node version: 18

**Comment by astuyve** [comment]
Thanks! We've taken this as a feature request and will close this issue when the work is complete.
