### ISSUE TITLE
Feature request: Enhanced metric for batch item failures

### ISSUE THREAD

**Issue by rg-lesmills** [DataDog/datadog-lambda-js#435]
At our company, most of our Lambda functions are batching SQS events and using [batchItemFailures for partial batch failures.](https://docs.aws.amazon.com/lambda/latest/dg/with-sqs.html#services-sqs-batchfailurereporting)

What this means practically is that Lambda will succeed, returning a list of failed events, rather than throwing an error.

Which means that the `aws.lambda.errors` and `aws.lambda.enhanced.errors` metrics are both useless, because even if the whole batch of events fails to process, the invocation is marked as a success.

It would be great if we could have a metric driven by the number of failed events (size of the `batchItemFailures` array in the response).

**Comment by astuyve** [comment]
Hi @rg-lesmills, thanks for reaching out!

Definitely. This is something we'll add as a feature request internally, and close this issue when it is released.

Thanks!

**Comment by duncanista** [comment]
This should be available in the next release!

**Comment by duncanista** [comment]
Closing due to latest release [v109](https://github.com/DataDog/datadog-lambda-js/releases/tag/v8.109.0) 🎉  being available!

**Comment by rg-lesmills** [comment]
@astuyve @duncanista @ssolmonson Thank you so much! 😄
