### ISSUE TITLE
Feature request: NodeJS 20.x layer

### ISSUE THREAD

**Issue by tlu-rs** [DataDog/datadog-lambda-js#436]
[AWS and Terraform now support Node.js 20.x Lambda runtime](https://github.com/aws/aws-sdk-go/blob/main/CHANGELOG.md#release-v1476-2023-11-08). Could we please get a Node.js 20.x layer? Thanks.

**Comment by astuyve** [comment]
Merged now and beginning the release, which I expect to take several hours. I'll update this when it is fully published.

Thanks!

**Comment by astuyve** [comment]
v100 is [out](https://github.com/DataDog/datadog-lambda-js/releases/tag/v7.100.0). We'll update the various development tools next. Thanks everyone!
