### ISSUE TITLE
Version 8.107.0 seems to be broken 

### ISSUE THREAD

**Issue by yuval-esggo** [DataDog/datadog-lambda-js#503]
## Expected Behavior
Lambda should behave just like last version, with no breaking changes in the code 

## Actual Behavior
When lambda runs with the same code and docker file it crashes when can't find the handler anymore 

## Steps to Reproduce the Problem

I just upgraded the package when reverting to 8.106.0 everything is great 

## Specifications

  - Datadog Lambda Layer version: 8.107.0
  - Node version: 20.11.1

## Stacktrace

  ```
2024-03-09T08:58:46.482Z	undefined	ERROR	Uncaught Exception 	{"errorType":"Runtime.ImportModuleError","errorMessage":"Error: Cannot find module 'handler'
Require stack:
- /var/runtime/index.mjs","stack":["Runtime.ImportModuleError: Error: Cannot find module 'handler'","Require stack:","- /var/runtime/index.mjs","    at _loadUserApp (file:///var/runtime/index.mjs:1087:17)","    at async UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1119:21)","    at async start (file:///var/runtime/index.mjs:1282:23)","    at async file:///var/runtime/index.mjs:1288:1"]}
  ```

**Comment by astuyve** [comment]
Thanks @yuval-esggo - I just published 8.107.1, can you confirm this is working for you now? I'll make a note not to use the release, I'm not sure what completely went wrong but will investigate to prevent this in the future.

Thanks!

**Comment by yuval-esggo** [comment]
Thanks, the patch is working properly!

**Comment by yuval-esggo** [comment]
Thanks, the patch is working properly!
