### ISSUE TITLE
Sending timer metrics

### ISSUE THREAD

**Issue by tovbinm** [DataDog/datadog-lambda-js#537]
Is there a way to send time elapsed (e.g. timer metrics) using datadog-lambda-js ?

**Comment by purple4reina** [comment]
You can do this using distribution metrics. In this doc, you'll want to replace the metric value with the duration you're looking to measure. https://docs.datadoghq.com/serverless/aws_lambda/metrics/?code-lang=nodejs#submit-custom-metrics-directly-from-a-lambda-function

**Comment by tovbinm** [comment]
Thanks. I will give it a try.
