### ISSUE TITLE
sendDistributionMetricWithDate no longer including tags

### ISSUE THREAD

**Issue by pedrovanzella** [DataDog/datadog-lambda-js#545]
## Expected Behavior
When calling `sendDistributionMetricWithDate`, some default tags are included:

* `account_id`
* `architecture`
* `aws_account`
* `env`
* `functioname`
* `region`
* `resource`

This used to be the case up until v8.108.

## Actual Behavior

Starting with v8.109, these tags are no longer included in the metrics. Tags are still included when calling `sendDistrubtionMetric` though.

## Specifications

  - Datadog Lambda Layer version: 109
  - Node version: 18

**Comment by duncanista** [comment]
Hey @pedrovanzella,

This should have been fixed in the [latest release ](https://github.com/DataDog/datadog-lambda-js/releases/tag/v9.113.0), or layer `113`.

Please feel free to re-open this issue if you have any other questions regarding this!
