### ISSUE TITLE
Release layer versions as GitHub releases

### ISSUE THREAD

**Issue by samchungy** [DataDog/datadog-lambda-js#556]
## Expected Behavior
I can use dependency management tooling on layers

## Actual Behavior
- I have to read release notes of a package to find the version to use

## Steps to Reproduce the Problem

  1. Use datadog CDK and manually specify layer versions
  2. Cry because nothing can update them.

## Specifications

  - Layer Versions are released as GitHub releases
  - https://github.com/DataDog/datadog-cdk-constructs/issues/232#issuecomment-2155878743

**Comment by duncanista** [comment]
Hey @samchungy,

Thanks for reaching out. I'm confused with the expected behavior. For your comment https://github.com/DataDog/datadog-cdk-constructs/issues/232#issuecomment-2155878743, if you look at the minor version of our package, that will be the layer version. For example, latest version is `v9.112.0`, which directly matches layer `112`, let me know if this is of help, or if there's anything else you propose we do.

Let me know if you have any questions!

**Comment by samchungy** [comment]
> Hey @samchungy,
> 
> Thanks for reaching out. I'm confused with the expected behavior. For your comment [DataDog/datadog-cdk-constructs#232 (comment)](https://github.com/DataDog/datadog-cdk-constructs/issues/232#issuecomment-2155878743), if you look at the minor version of our package, that will be the layer version. For example, latest version is `v9.112.0`, which directly matches layer `112`, let me know if this is of help, or if there's anything else you propose we do.
> 
> Let me know if you have any questions!

Oooo that might work. I'll have to play around with Renovate.

With renovate you can tell it to track versions based on releases, so I was hoping that this repo could post releases with the exact version.

Eg. this repo could publish GitHub releases similar to how a changesets monorepo would.

Eg. a datadog-lambda-js@9.112.0 release alongside lambda-layer@112

**Comment by samchungy** [comment]
Okay, figured out a way to work with that. Cheers @duncanista 

https://github.com/samchungy/renovate-experiments/pull/8

For prosperity: 

My code looks like:

```ts
const datadog = new Datadog(this, 'datadog', {
  apiKeySecret: datadogSecret,
  addLayers: false,
  enableDatadogLogs: false,
  flushMetricsToLogs: false,
  extensionLayerVersion: 58,
  // renovate: depName=DataDog/datadog-lambda-js
  nodeLayerVersion: 111,
});
```

My renovate config:

```json
{
  customManagers: [
    {
      customType: 'regex',
      fileMatch: ['test.ts'],
      // This allows us to use the non breaking space to prefix plugins in diffs which we do not want Renovate to update
      matchStrings: [
        'Datadog\\([\\S\\s]+nodeLayerVersion:\\s?(?<currentValue>\\d+)',
      ],
      depNameTemplate: 'DataDog/datadog-lambda-js',
      extractVersionTemplate: '^v\\d+\\.(?<version>\\d+)\\..*',
      datasourceTemplate: 'github-releases',
    },
  ],
}
```

**Comment by duncanista** [comment]
Hey @samchungy ,

Thanks for sharing your insights on this!

Again, sorry we cannot provide an automatic layer updater like the Serverless Plugin, yet.
But please, feel free to re-open the issue whenever you feel like needing it.

Feel free to ping me back or send me an email at jgb@datadoghq.com if you want to send me direct feedback!
